services:
  chip8pp:
    image: chip8pp:latest
    environment:
      - DISPLAY=${DISPLAY}
      - SCALE=${SCALE}
      - DELAY=${DELAY}
      - PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native
      - ~/.config/pulse/cookie:/root/.config/pulse/cookie
      - ${ROM_DIR_PATH}:/roms
    devices:
      - /dev/snd
    entrypoint: ["./build/emulator"]
    command: ["/${ROM_DIRNAME}/${ROM_FILENAME}", "${SCALE}", "${DELAY}"]
    stdin_open: true
    tty: true
